version: '3.8'
services:
  web:
    container_name: sudoku_flask
    build: .
    command: gunicorn -b 0.0.0.0:5000 app:app
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - '5000:5000'
    depends_on:
      - redis

  celery:
    build: .
    container_name: sudoku_celery
    command: celery -A tasks.celery worker --loglevel=info --logfile=celery.log
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  dashboard:
    build: .
    container_name: sudoku_celery_dashboard
    command: celery flower --broker=redis://redis:6379/0 --port=5555
    restart: on-failure
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery

  redis:
    image: "redis:alpine"
    container_name: sudoku_redis
    restart: on-failure
    command: redis-server
    ports:
     - "6379:6379"